# .PHONY: build
# build:
# 	@echo "$(FILE)"
# 	@echo "$(FILE)"


FILE := $(word 2, $(MAKECMDGOALS))
TARGET := $(word 1, $(MAKECMDGOALS))


# $(MAKECMDGOALS): build
# # If the first argument is "run"...
# ifeq (run,$(firstword $(MAKECMDGOALS)))
#   # use the rest as arguments for "run"
#   RUN_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
#   # ...and turn them into do-nothing targets
#   $(eval $(RUN_ARGS):;@:)
# endif
